### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by KnorpelSenf** [Helloyunho/mdoc#3]
Breaks when used on [grammY](http://git.io/grammyjs).

```bash
git clone git@github.com:grammyjs/grammY.git
cd grammY/src
denodown mod.ts
```
results in
```
error: Uncaught (in promise) TypeError: node.jsDoc.split is not a function
          .split('\n')
           ^
    at functionToMarkdown (https://deno.land/x/denodown@v0.1.3/parser/functions.ts:24:12)
    at https://deno.land/x/denodown@v0.1.3/utils/generate.ts:38:23
    at Array.forEach (<anonymous>)
    at generateMarkdown (https://deno.land/x/denodown@v0.1.3/utils/generate.ts:36:22)
    at main (https://deno.land/x/denodown@v0.1.3/index.ts:84:24)
```

**Comment by Helloyunho** [comment]
Hmm, maybe Deno changed the doc json a bit
Anyway thanks for the report!

**Comment by KnorpelSenf** [comment]
> Hmm, maybe Deno changed the doc json a bit

Perhaps we should consume the type definitions directly from their GitHub repo, instead of copying them to this project? This may be brittle, but at least we have a good chance of getting compilation errors that tell us when something stops working.

**Comment by KnorpelSenf** [comment]
Oh hang on … I did not consider that the site isn't using Deno yet. I think copying is hard to avoid then.

**Comment by KnorpelSenf** [comment]
And updates on this? Would you recommend me to fork the project and start maintaining it myself? I am unsure how much time you would like to spend on this.

**Comment by Helloyunho** [comment]
> Would you recommend me to fork the project and start maintaining it myself?

If you want you can fork the project and maintain it
But I soon get a big free times so maybe I can do something about this soon

**Comment by KnorpelSenf** [comment]
I am mostly busy with other things, so I will wait. You can ping me here if you discover that you do not have the time.

I think I would prefer to contribute to this repo via PRs instead of rolling a fork. That is, if you are able to review and merge, which seems to be the case :)

**Comment by KnorpelSenf** [comment]
The new design of https://doc.deno.land is substantially better because it is super fast, statically rendered, and has a better overview. I no longer think I will use this tool because it does not make as much sense to integrate the API into my VuePress site.

I will keep this open for reference.
